Portfolio: desktop version
MohammadYaser/My-Portfolio pull request #4
Opened 2023-06-16 05:25 UTC by MohammadYaser

-Added desktop images
-Modified index.html file
-Modified style.css file
-Updated navbar
-Added animation and transition
-Added media queries

2023-06-16 07:51 UTC, Efiamotu-1 requested changes
Hi @MohammadYaser , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 07:51 UTC, Efiamotu-1 commented on Index.html
- [ ] Your design for the works section on desktop doesn't match the figma template as shown from the images below please kindly correct the flaw in your project design. It is important that your design matches correctly the provided figma template as this shows your attention to details as a frontend developer and this is a good skill to have :+1:
- [ ] Ensure you make use of the appropriate colors and fonts as provided in the figma template and shown in the images below. :+1: 
- figma design
![w-s](https://github.com/MohammadYaser/Portfolio/assets/89055502/ca447040-bfe3-46e1-891c-63484a4348fa)
- your design
![ws](https://github.com/MohammadYaser/Portfolio/assets/89055502/a2562f5d-0da0-4418-9b56-da9ad48c58bc)

2023-06-16 07:51 UTC, Efiamotu-1 commented on Index.html
- [ ] Please kindly work on the spacing between each card as shwon in the figma template below. currently your page doesn'y match the provided design and i used red lines to show you where adjustments are to be made i suggest you work on this before resubmitting :+1: 
- figma design
![6-c](https://github.com/MohammadYaser/Portfolio/assets/89055502/229a3454-76d3-4314-a862-113625b8f6f5)
- your design
![6c](https://github.com/MohammadYaser/Portfolio/assets/89055502/b413c34f-85f9-46a2-9d15-d0771cf5deba)

2023-06-16 07:51 UTC, Efiamotu-1 commented on Index.html
- [ ] Your technologies are not properly centered as shown in the images below. please i suggest you kindly center it properly within the section :+1: 
- figma design
![tc](https://github.com/MohammadYaser/Portfolio/assets/89055502/d3236872-2ea0-4514-82cc-5e94251c145a)
- your design
![ct](https://github.com/MohammadYaser/Portfolio/assets/89055502/cd5d21f6-5e98-444d-b865-55e7aa3d733e)

2023-06-16 07:51 UTC, Efiamotu-1 commented on Index.html
- [ ] Please center the contact me section of your portfolio website as shown in the figma design below. It is important that your design matches correctly the provided figma template as this shows your attention to details as a frontend developer and this is a good skill to have :+1:
- figma design
![ccm](https://github.com/MohammadYaser/Portfolio/assets/89055502/da514358-e7f9-4a90-a579-da7992783f20)

2023-06-16 07:51 UTC, Efiamotu-1 commented on Index.html
- [ ] As shown in the figma image below your icons don'y use the proper color and are not clearly visible like the provided figma design pleased i suggest you kindly fix this design flaw to make your project aesthetically pleasing. It is important that your design matches correctly the provided figma template as this shows your attention to details as a frontend developer and this is a good skill to have :+1:
- figma design
![ftt](https://github.com/MohammadYaser/Portfolio/assets/89055502/fd347618-70ff-4608-a960-12c3b5a07d18)
- your design
![ft](https://github.com/MohammadYaser/Portfolio/assets/89055502/455df932-7872-42d5-b97b-f267765f271e)

2023-06-16 07:51 UTC, Efiamotu-1 commented on Index.html
- [ ] In implementing all of the required changes always check to see that the design for mobile version is still correctly showing as provided in the figma template :+1: :sparkles:

2023-06-16 13:35 UTC, Zuhaib042 requested changes
Hi @MohammadYaser 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/NSMvVni9vpHvz4RoUN/giphy.gif)

 ## Highlights
✅ Linters passing
✅ Descriptive PR

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 13:35 UTC, Zuhaib042 commented on Index.html
> +              <button type="submit" class="animate-btn button4 button2 button1-text">See Project</button>
- [ ] As mentioned by the previous reviewer, kindly consider adjusting headings and `li` tags in these projects' cards to make sure they look identical to the figma design. I checked yours and they still are not in the same position as they are in the figma.
your design
![q](https://github.com/MohammadYaser/Portfolio/assets/96683843/c0b06885-0d13-45f4-9920-e63737b725de)

figma design
![as](https://github.com/MohammadYaser/Portfolio/assets/96683843/dad0ceac-0d3a-4b19-b6ec-07b925b53d74)

- [OPTIONAL] Also kindly consider adding the hover styling to these projects' cards. this requirement was missed by the previous reviewer. so the requirement is: when the user hovers over these cards, then the cards' description disappears and a red `see project` button appears as shown in the figma design.
![r](https://github.com/MohammadYaser/Portfolio/assets/96683843/88456273-0bd8-4e41-a16d-f809f504e319)

2023-06-16 13:35 UTC, Zuhaib042 commented on Index.html
> +          </form>
- [ ] Your contact section is not identical to the figma design as per requirements and suggested changes by the previous reviewer. 
  - kindly consider to a lot 40% width to the left heading in this section and 60% width to the left side form sub- 
   section.
  - Also make sure to give appropriate margins to these sub-sections as in the figma design 
  - You can also choose to take one input for the Full name (just like the mobile version) as it is flexible by microverse.
  figma design
![t](https://github.com/MohammadYaser/Portfolio/assets/96683843/84e89514-3d86-487c-92af-c3083b099479)

2023-06-17 14:05 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @MohammadYaser  , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 14:05 UTC, ademibowale commented on Style.css
> +  font-style: bold;
- [ ] Kudos to you ,you are doing a great job but  its mandatory to review your projectproperly before approve kindly make this changes quickly and resubmit i can see you still have 3 review extra so pls make this changes and resubmit .

- [ ] According to your previouse review  which says `In implementing all of the required changes always check to see that the design for mobile version is still correctly showing as provided in the figma template 👍 ` see here ✨https://github.com/MohammadYaser/Portfolio/pull/4#discussion_r1231911431 kindly consider to work more on your mobile version to be more responsive and look exact like the figma template this will make your website look professional.  

your mobile design 
![Screenshot 2023-06-17 144441](https://github.com/MohammadYaser/Portfolio/assets/92458236/d52cb589-db17-4bf5-915b-572fe1d07b5e)

2023-06-17 14:28 UTC, MohammadYaser commented on Style.css
> +  font-style: bold;
![image](https://github.com/MohammadYaser/Portfolio/assets/134836471/9dbe4921-1dee-42d9-ac45-f724ac6eaef7)
This is my Updated design

2023-06-17 16:12 UTC, Zuhaib042 requested changes
Hi @MohammadYaser 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/3o7qDQAFlF8mZjv6fK/giphy.gif)

 ## Highlights
✅ Linters passing
✅ Professional Readme

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 16:12 UTC, Zuhaib042 commented on Style.css
> +  align-items: flex-start;
- [ ] As suggested by the previous reviewer, the project cards in your projects section are aligned to the left wide on the mobile display. they should be aligned in the center properly. I have the fix for you, you just need to change the line 145 to `align-items: center;` to make it centered.
your design
<img width="539" alt="Screenshot 2023-06-17 at 9 01 54 PM" src="https://github.com/MohammadYaser/Portfolio/assets/96683843/0cf1d1b5-9139-4e87-8511-d11d49e18cd8">

2023-06-17 16:50 UTC, Efiamotu-1 approved these changes
Hi @MohammadYaser , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* Good PR Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 17:37 UTC, merged